# Copyright (C) 2024  The publishing-tools Project by the Science HPC Center at UCPH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

environments:
  publishing_tools:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: "{{SECRET:[publishing_tools][username]}}"
      PYPI_PASSWORD: "{{SECRET:[publishing_tools][password]}}"
    pipelines:
      - publishing-tools
pipelines:
  publishing-tools:
    group: pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      publishing-tools_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/publishing-tools.git
        branch: main
        destination: publishing-tools
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        branch: main
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: publishing-tools
      TEST_DIRECTORY: publishing-tools
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package