environments:
  publish_container_tools:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: "{{SECRET:[publish_container_tools][username]}}"
      PYPI_PASSWORD: "{{SECRET:[publish_container_tools][password]}}"
    pipelines:
      - publish-container-tools
pipelines:
  publish-container-tools:
    group: pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      publish-container-tools_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/publish-container-tools.git
        branch: main
        destination: publish-container-tools
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        branch: main
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: publish-container-tools
      TEST_DIRECTORY: publish-container-tools
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package